/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.hdm82digital.lojagames.view;

/**
 *
 * @author will
 */
public class CadastroView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroView.class.getName());

    /**
     * Creates new form CadastroView
     */
    public CadastroView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelParentCadastro = new javax.swing.JPanel();
        jPanelSideBar = new javax.swing.JPanel();
        jPanelFormCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeCadastro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmailCadastro = new javax.swing.JTextField();
        jButtonCadastro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JLabelLogarConta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldSenhaCadastro = new javax.swing.JPasswordField();
        jPanelLogo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelContenPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelParentCadastro.setLayout(new java.awt.GridLayout());

        jPanelSideBar.setBackground(new java.awt.Color(26, 31, 36));

        jPanelFormCadastro.setBackground(new java.awt.Color(26, 31, 36));

        jLabel2.setBackground(new java.awt.Color(11, 30, 31));
        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome");

        jTextFieldNomeCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(11, 30, 31));
        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");

        jLabel4.setBackground(new java.awt.Color(11, 30, 31));
        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha");

        jTextFieldEmailCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jButtonCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastro.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jButtonCadastro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastro.setText("Criar conta");
        jButtonCadastro.addActionListener(this::jButtonCadastroActionPerformed);

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Não tem login?");

        JLabelLogarConta.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        JLabelLogarConta.setForeground(new java.awt.Color(0, 153, 255));
        JLabelLogarConta.setText("Voltar");
        JLabelLogarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLabelLogarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabelLogarContaMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CADASTRO");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPasswordFieldSenhaCadastro.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelFormCadastroLayout = new javax.swing.GroupLayout(jPanelFormCadastro);
        jPanelFormCadastro.setLayout(jPanelFormCadastroLayout);
        jPanelFormCadastroLayout.setHorizontalGroup(
            jPanelFormCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelFormCadastroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelFormCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFormCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabelLogarConta))
                    .addGroup(jPanelFormCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonCadastro)
                        .addGroup(jPanelFormCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPasswordFieldSenhaCadastro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmailCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelFormCadastroLayout.setVerticalGroup(
            jPanelFormCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButtonCadastro)
                .addGap(26, 26, 26)
                .addGroup(jPanelFormCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JLabelLogarConta))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelLogo.setBackground(new java.awt.Color(26, 31, 36));
        jPanelLogo.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanelLogo.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(26, 31, 36));
        jLabel7.setIcon(new javax.swing.ImageIcon("/home/will/NetBeansProjects/lojagames/src/main/resources/br/com/hdm82digital/lojagames/imgs/logo.png")); // NOI18N
        jPanelLogo.add(jLabel7, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanelSideBarLayout = new javax.swing.GroupLayout(jPanelSideBar);
        jPanelSideBar.setLayout(jPanelSideBarLayout);
        jPanelSideBarLayout.setHorizontalGroup(
            jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSideBarLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jPanelFormCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(jPanelSideBarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSideBarLayout.setVerticalGroup(
            jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFormCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanelParentCadastro.add(jPanelSideBar);

        jPanelContenPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/will/NetBeansProjects/lojagames/src/main/resources/br/com/hdm82digital/lojagames/imgs/splash.png")); // NOI18N
        jPanelContenPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanelParentCadastro.add(jPanelContenPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParentCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParentCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void JLabelLogarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelLogarContaMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginView loginView = new LoginView();
        loginView.setLocationRelativeTo(null);
        loginView.setVisible(true);
    }//GEN-LAST:event_JLabelLogarContaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        javax.swing.UIManager.put("Button.arc", 15);
        javax.swing.UIManager.put("Component.arc", 15); // Afeta TextFields, PasswordFields, etc.
        javax.swing.UIManager.put("TextComponent.arc", 15);
        com.formdev.flatlaf.FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelLogarConta;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelContenPanel;
    private javax.swing.JPanel jPanelFormCadastro;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelParentCadastro;
    private javax.swing.JPanel jPanelSideBar;
    private javax.swing.JPasswordField jPasswordFieldSenhaCadastro;
    private javax.swing.JTextField jTextFieldEmailCadastro;
    private javax.swing.JTextField jTextFieldNomeCadastro;
    // End of variables declaration//GEN-END:variables
}
