/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.hdm82digital.lojagames.view;

import br.com.hdm82digital.lojagames.repository.ClienteRepository;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author will
 */
public class ClientesView extends javax.swing.JPanel {

    /**
     * Creates new form ClientesView
     */
    public ClientesView() {
        initComponents();

        JTableClientes.setBackground(new java.awt.Color(44, 52, 60)); // #2C343C
        JTableClientes.setForeground(new java.awt.Color(255, 255, 255)); // Texto branco

        // Pinta a área vazia do ScrollPane para não ficar cinza-claro
        if (JTableClientes.getParent() != null && JTableClientes.getParent().getParent() instanceof javax.swing.JScrollPane) {
            javax.swing.JScrollPane scroll = (javax.swing.JScrollPane) JTableClientes.getParent().getParent();
            scroll.getViewport().setBackground(new java.awt.Color(44, 52, 60));
            scroll.setBorder(javax.swing.BorderFactory.createEmptyBorder()); // Remove bordas brancas feias
        }

        // Configuração visual das linhas (Estilo Zebrado)
        JTableClientes.setShowHorizontalLines(true);
        JTableClientes.setShowVerticalLines(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIDGame = new javax.swing.JTextField();
        jButtonAdicionarJogo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableClientes = new javax.swing.JTable();
        jButtonEditarJogo = new javax.swing.JButton();
        jButtonApagarJogo = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 39, 45));
        setPreferredSize(new java.awt.Dimension(950, 650));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GERENCIAMENTO DE CLIENTES");

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(160, 170, 178));
        jLabel2.setText("Cliente:");

        jTextFieldNomeCliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeCliente.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldNomeCliente.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNomeCliente.addActionListener(this::jTextFieldNomeClienteActionPerformed);

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(160, 170, 178));
        jLabel5.setText("Email:");

        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldEmail.addActionListener(this::jTextFieldEmailActionPerformed);

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(160, 170, 178));
        jLabel6.setText("Tel:");

        jTextFieldTelefone.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTelefone.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldTelefone.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldTelefone.addActionListener(this::jTextFieldTelefoneActionPerformed);

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(160, 170, 178));
        jLabel7.setText("ID Game:");

        jTextFieldIDGame.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIDGame.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jTextFieldIDGame.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldIDGame.addActionListener(this::jTextFieldIDGameActionPerformed);

        jButtonAdicionarJogo.setBackground(new java.awt.Color(46, 204, 113));
        jButtonAdicionarJogo.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jButtonAdicionarJogo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAdicionarJogo.setText("Cadastrar");
        jButtonAdicionarJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarJogo.addActionListener(this::jButtonAdicionarJogoActionPerformed);

        JTableClientes.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        JTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Telefone", "ID Game"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableClientes);

        jButtonEditarJogo.setBackground(new java.awt.Color(241, 196, 15));
        jButtonEditarJogo.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jButtonEditarJogo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditarJogo.setText("Editar");
        jButtonEditarJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditarJogo.addActionListener(this::jButtonEditarJogoActionPerformed);

        jButtonApagarJogo.setBackground(new java.awt.Color(231, 76, 60));
        jButtonApagarJogo.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jButtonApagarJogo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonApagarJogo.setText("Apagar");
        jButtonApagarJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonApagarJogo.addActionListener(this::jButtonApagarJogoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDGame, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jButtonAdicionarJogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditarJogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonApagarJogo)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldIDGame, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAdicionarJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonApagarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeClienteActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneActionPerformed

    private void jTextFieldIDGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDGameActionPerformed

    private void jButtonAdicionarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarJogoActionPerformed

    private void jButtonEditarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarJogoActionPerformed

    private void jButtonApagarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApagarJogoActionPerformed

    private void JTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableClientesMouseClicked
        int linhaSelecionada = JTableClientes.getSelectedRow();

        if (linhaSelecionada != -1) {
            String id = JTableClientes.getValueAt(linhaSelecionada, 0).toString();
            String cliente = JTableClientes.getValueAt(linhaSelecionada, 1).toString();
            String email = JTableClientes.getValueAt(linhaSelecionada, 2).toString();
            String telefone = JTableClientes.getValueAt(linhaSelecionada, 3).toString();
            String IDGame = JTableClientes.getValueAt(linhaSelecionada, 4).toString();

            jTextFieldNomeCliente.setText(cliente);
            jTextFieldEmail.setText(email);
            jTextFieldTelefone.setText(telefone);
            jTextFieldIDGame.setText(IDGame);

            // id temporario
            jTextFieldNomeCliente.setName(id);
        }
    }//GEN-LAST:event_JTableClientesMouseClicked

    public void atualizarTabela() {
        ClienteRepository repo = new ClienteRepository();
        List<Object[]> clientes = repo.listarTodos();
        DefaultTableModel modelo = (DefaultTableModel) JTableClientes.getModel();
        modelo.setRowCount(0);
        for (Object[] cliente : clientes) {
            modelo.addRow(cliente);
        }
    }

    private void limparCampos() {
        jTextFieldNomeCliente.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldIDGame.setText("");
        jTextFieldNomeCliente.setName("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableClientes;
    private javax.swing.JButton jButtonAdicionarJogo;
    private javax.swing.JButton jButtonApagarJogo;
    private javax.swing.JButton jButtonEditarJogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIDGame;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
