/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.hdm82digital.lojagames.view;

/**
 *
 * @author will
 */
public class LoginView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        setLocationRelativeTo(null);
        //488
        //624
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParentLogin = new javax.swing.JPanel();
        jPanelSideBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFormLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmailLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldSenhaLogin = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JLabelCriarConta = new javax.swing.JLabel();
        jLabelEsquecerSenha = new javax.swing.JLabel();
        jPanelLogo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelContentPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 0));
        setResizable(false);

        ParentLogin.setBackground(new java.awt.Color(255, 255, 255));
        ParentLogin.setLayout(new java.awt.GridLayout(1, 2));

        jPanelSideBar.setBackground(new java.awt.Color(26, 31, 36));
        jPanelSideBar.setPreferredSize(new java.awt.Dimension(200, 400));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanelFormLogin.setBackground(new java.awt.Color(26, 31, 36));
        jPanelFormLogin.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(11, 30, 31));
        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");

        jTextFieldEmailLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");

        jPasswordFieldSenhaLogin.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Entrar");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Não tem login?");

        JLabelCriarConta.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        JLabelCriarConta.setForeground(new java.awt.Color(0, 153, 255));
        JLabelCriarConta.setText("Criar conta");
        JLabelCriarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLabelCriarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabelCriarContaMouseClicked(evt);
            }
        });

        jLabelEsquecerSenha.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabelEsquecerSenha.setForeground(new java.awt.Color(0, 153, 255));
        jLabelEsquecerSenha.setText("Esqueci a senha");
        jLabelEsquecerSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEsquecerSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEsquecerSenhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormLoginLayout = new javax.swing.GroupLayout(jPanelFormLogin);
        jPanelFormLogin.setLayout(jPanelFormLoginLayout);
        jPanelFormLoginLayout.setHorizontalGroup(
            jPanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelFormLoginLayout.createSequentialGroup()
                        .addComponent(jLabelEsquecerSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFormLoginLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JLabelCriarConta))
                        .addGroup(jPanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldEmailLogin)
                            .addComponent(jPasswordFieldSenhaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanelFormLoginLayout.setVerticalGroup(
            jPanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLoginLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabelEsquecerSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JLabelCriarConta))
                .addGap(17, 17, 17))
        );

        jPanelLogo.setBackground(new java.awt.Color(26, 31, 36));
        jPanelLogo.setLayout(new java.awt.BorderLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/will/NetBeansProjects/lojagames/src/main/resources/br/com/hdm82digital/lojagames/imgs/logo.png")); // NOI18N
        jPanelLogo.add(jLabel5, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelSideBarLayout = new javax.swing.GroupLayout(jPanelSideBar);
        jPanelSideBar.setLayout(jPanelSideBarLayout);
        jPanelSideBarLayout.setHorizontalGroup(
            jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSideBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSideBarLayout.setVerticalGroup(
            jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ParentLogin.add(jPanelSideBar);

        jPanelContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContentPanel.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("/home/will/NetBeansProjects/lojagames/src/main/resources/br/com/hdm82digital/lojagames/imgs/splash.png")); // NOI18N
        jPanelContentPanel.add(jLabel6, java.awt.BorderLayout.CENTER);

        ParentLogin.add(jPanelContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLabelCriarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelCriarContaMouseClicked
        this.dispose();
        CadastroView cadastroView = new CadastroView();
        cadastroView.setLocationRelativeTo(null);
        cadastroView.setVisible(true);
    }//GEN-LAST:event_JLabelCriarContaMouseClicked

    private void jLabelEsquecerSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEsquecerSenhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEsquecerSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        javax.swing.UIManager.put("Button.arc", 15);
        javax.swing.UIManager.put("Component.arc", 15); // Afeta TextFields, PasswordFields, etc.
        javax.swing.UIManager.put("TextComponent.arc", 15);
        com.formdev.flatlaf.FlatDarkLaf.setup();
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelCriarConta;
    private javax.swing.JPanel ParentLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEsquecerSenha;
    private javax.swing.JPanel jPanelContentPanel;
    private javax.swing.JPanel jPanelFormLogin;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelSideBar;
    private javax.swing.JPasswordField jPasswordFieldSenhaLogin;
    private javax.swing.JTextField jTextFieldEmailLogin;
    // End of variables declaration//GEN-END:variables
}
